meupcLista = ["GABINETE COOLER MASTER","GEFORCE RTX 2080 TI"," PLACA MAE BIOSTAR X470 GT8 RACING"," MEMORIA TEAM GROUP T-FORCE VULCAN PICHAU 8GB"," FONTE PICHAU GAMING NIDUS 500W BRONZE 80 PLUS"," PROCESSADOR AMD RYZEN 5 3600 HEXA-CORE 3.6GHZ "," COOLER DEEPCOOL GAMMAXX 300R LED VERMELHO,"," SSD KINGSTON A400 240GB",]
print("Meu pc dos sonhos: ",meupcLista)

meupcLista.remove("GABINETE COOLER MASTER")
meupcLista.remove("GEFORCE RTX 2080 TI")
print("Minha lista com o gabinete e a placa de video removidas: ", meupcLista)
